name: Trigger Remote Workflow

on:
  push:
    branches:
      - main  # or the branch you want to trigger from

jobs:
  test-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.REMOTE_GITHUB_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/AshotEliteDev/myrepo-pro/actions/workflows/pro.yml/dispatches \
            -d '{"ref":"main","inputs":{"trigger_uuid":"${{ github.sha }}"}}'
