name: Clone TC Private Repo

on:
  push:

jobs:
  clone-tc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Myrepo repository
      - name: Checkout Myrepo Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Clone TC Private Repository using the GitHub PAT
      - name: Clone TC Private Repository
        run: |
          git clone https://${{ secrets.REMOTE_GITHUB_KEY }}@github.com/AshotEliteDev/tc.git tc
        env:
          # Ensure you are using the correct secret containing your Personal Access Token
          REMOTE_GITHUB_KEY: ${{ secrets.REMOTE_GITHUB_KEY }}
      # Step 3: Run the my-build.sh script from TC
      - name: Run TC Build Script
        run: |
          cd tc
          sh ./sh/my-build.sh  # Adjust the path to your script if necessary
      # Step 4: List the contents of both repositories (Myrepo and TC) to verify
      - name: List Directory
        run: ls -al
