name: Trigger Elementor Pro Tests

on:
  pull_request:
    branches:
      - test-1  # Specify the branch for pull request events
    types:
      [ labeled ]

jobs:
  check-label:
    if: contains(github.event.label.name, 'run-pro-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Elementor-Pro Tests From Core
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/AshotEliteDev/tc/actions/workflows/main.yaml/dispatches \
            -d '{"ref":"test-1","inputs":{"trigger_uuid":"${{ github.sha }}"}}'


# name: Trigger Remote Workflow

# on:
#   pull_request:
#     types:
#       - labeled  # or the branch you want to trigger from

# jobs:
#   test-test:
#     if: contains(github.event.label.name, 'ggg-pr')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Remote Workflow
#         run: |
#           curl -X POST \
#             -H "Authorization: token ${{ secrets.REMOTE_GITHUB_KEY }}" \
#             -H "Accept: application/vnd.github.v3+json" \
#             https://api.github.com/repos/AshotEliteDev/myrepo-pro/actions/workflows/pro.yml/dispatches \
#             -d '{"ref":"main","inputs":{"trigger_uuid":"${{ github.sha }}"}}'
