 name: Trigger Remote Workflow

 on:
   push:
    branches:
      - main
   # pull_request:
   #   types:
   #     - labeled  # or the branch you want to trigger from

 jobs:
   test-test:
     # if: contains(github.event.label.name, 'ggg-pr')
     runs-on: ubuntu-latest
     steps:
       - name: Trigger Remote Workflow
         run: |
           response=$(curl -X POST \
             -H "Authorization: token ${{ secrets.REMOTE_GITHUB_KEY }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d '{"event_type": "run-tc-workflow", "client_payload": {"branch": "dev1"}}' \
             https://api.github.com/repos/AshotEliteDev/tc/dispatches)
           
           echo "Response: $response"
       
         # run: |
         #   curl -X POST \
         #     -H "Authorization: token ${{ secrets.REMOTE_GITHUB_KEY }}" \
         #     -H "Accept: application/vnd.github.v3+json" \
         #     https://api.github.com/repos/AshotEliteDev/tc/actions/workflows/main.yml/dispatches \
         #     -d '{"ref":"main","inputs":{"trigger_uuid":"${{ github.sha }}", "custom_value": "Steve Jobs"}}'
             
             
        # -d '{"event_type": "run-tc-workflow", "client_payload": {"branch": "dev1"}}'
       
             
