name: Trigger Remote Workflow

on:
  push:
  pull_request:
    types:
       [ labeled ]  # or the branch you want to trigger from

jobs:
  test-test:
    if: contains(github.event.label.name, 'ggg-pr')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REMOTE_GITHUB_KEY }}
          repository: AshotEliteDev/tc
          event-type: trigger-tests
          client-payload: '{"ref": "main", "inputs": {"trigger_uuid": "${{ github.sha }}"}}'
