name: Run Elementor Pro Playwrights

on:
#  pull_request:
#    types: [ labeled ]
  push:

jobs:
  clone-and-build:
#    if: contains(github.event.pull_request.labels.*.name, 'run-pw-tests')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Elementor Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Cache Elementor Node Modules
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'elementor/elementor-pro'
      #     path: ${{ github.workspace }}
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone Elementor-Pro Repository
        run: |
          # Step 1: Configure Git user details
          git config --global user.name "baghdasarovelementor"
          git config --global user.email "norayrb@elementor.red"
      
          # Step 2: Clone the Elementor-Pro repository
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/elementor/elementor-pro.git ~/elementor-pro
      
          # Step 3: Change directory to the cloned repository
          cd ~/elementor-pro
      
          # Step 4: Fetch all branches and check out the specified SHA
          git fetch --all
          git checkout ${{ github.sha }}  # Use the SHA from the push event
      
          # Step 5: Install dependencies and build
          npm ci && npx grunt
        # run: |
        #   cd ${{ github.workspace }}  # Ensure you are in the correct working directory
        #   git clone "https://${{ secrets.GITHUB_TOKEN }}@github.com/elementor/elementor-pro.git" elementor-pro
        #   cd elementor-pro
        #   git checkout ${{ github.sha }}  # Checkout the SHA that triggered the workflow

      # - name: Install & Build Elementor-Pro
      #   run: |
      #     cd ${{ github.workspace }}/elementor-pro
      #     npm ci  # Install dependencies
      #     npx grunt  # Build Elementor-Pro

      # - name: Cache Elementor-Pro Node Modules
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-elementor-pro-node-modules
      #   with:
      #     path: ${{ github.workspace }}/elementor-pro/node_modules
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('elementor-pro/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      - name: Trigger Playwright Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "trigger-from-core", "client_payload": {"branch": "${{ github.sha }}"}}' \
            https://api.github.com/repos/elementor/elementor-pro/dispatches
