name: Run Elementor Pro Playwrights

on:
  push:  # Replace this with the actual trigger

jobs:
  clone-tc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Elementor repository
      - name: Checkout Elementor Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Cache node modules
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Step 3: Clone Elementor-Pro Repository
      - name: Clone Elementor-Pro Repository
        run: |
          # Step 1: Configure Git user details
          git config --global user.name "baghdasarovelementor"
          git config --global user.email "norayrb@elementor.red"

          # Step 2: Clone the Elementor-Pro repository using the PAT
          git clone "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/elementor/elementor-pro.git" ~/elementor-pro

          # Step 3: Change directory to the cloned repository
          cd ~/elementor-pro

          # Step 4: Fetch all branches and check out the specified SHA
          git fetch --all
          git checkout ${{ github.sha }}  # Use the SHA from the push event

          # Step 5: Install dependencies and build
          npm ci && npx grunt

      # Step 4: Save Pro Build to Cache (if needed)
      - name: Save Pro Build to Cache
        uses: actions/cache@v2
        env:
          key: ${{ github.sha }}-pro
        with:
          path: ~/elementor-pro
          key: ${{ env.key }}
          restore-keys: ${{ env.key }}
